# Generated by Django 5.2 on 2025-04-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fin_pessoal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receitas',
            name='data_atualizacao',
        ),
        migrations.AddField(
            model_name='receitas',
            name='previsao',
            field=models.CharField(blank=True, max_length=255, verbose_name='previsao'),
        ),
    ]
