# Generated by Django 5.2 on 2025-04-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fin_pessoal', '0002_remove_receitas_data_atualizacao_receitas_previsao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitas',
            name='status',
            field=models.CharField(max_length=255, verbose_name='status'),
        ),
    ]
