# Generated by Django 5.2 on 2025-04-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fin_pessoal', '0003_alter_receitas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitas',
            name='fornecedor',
            field=models.CharField(max_length=255, verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='previsao',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='status',
            field=models.CharField(max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='tipo',
            field=models.CharField(max_length=255, verbose_name='Tipo'),
        ),
    ]
