# Generated by Django 5.2 on 2025-04-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fin_pessoal', '0004_alter_receitas_fornecedor_alter_receitas_previsao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitas',
            name='parcela',
            field=models.DateField(blank=True, null=True, verbose_name='Parcela'),
        ),
    ]
