# Generated by Django 5.2 on 2025-04-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fin_pessoal', '0005_receitas_parcela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitas',
            name='parcela',
            field=models.CharField(blank=True, null=True, verbose_name='Parcela'),
        ),
    ]
