# Generated by Django 5.2 on 2025-04-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fin_pessoal', '0006_alter_receitas_parcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitas',
            name='categoria',
            field=models.CharField(blank=True, null=True, verbose_name='Categoria'),
        ),
    ]
