# Generated by Django 5.2 on 2025-05-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fin_pessoal', '0007_receitas_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255, verbose_name='Tipo')),
                ('categ', models.CharField(max_length=255, verbose_name='Categoria')),
            ],
        ),
    ]
