# Generated by Django 5.2 on 2025-05-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fin_pessoal', '0008_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitas',
            name='natureza',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Natureza'),
        ),
    ]
